name: putter
version: 0.1.0
publish_to: 'none'
description: A cross-platform torrent search app, ported from Python to Dart with flutter.
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
