name: putter
version: 0.1.0
publish_to: 'none'
description: A cross-platform torrent search app, ported from Python to Dart with flutter.
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  html: ^0.15.4
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_inappwebview: ^6.1.5
  flutter_inappwebview_platform_interface: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true